version: '3.5'
services:
  website:
    build: .
    networks:
      - 'dmz'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.website.rule=Host(`gsr.jenspots.com`)'
      - 'traefik.http.routers.website.entrypoints=websecure'
      - 'traefik.http.routers.website.tls.certresolver=letsencrypt'
      - 'traefik.http.services.website.loadbalancer.server.port=3000'
      - 'com.centurylinklabs.watchtower.enable="false"'

      networks:
        - 'gsr'
      restart: unless-stopped

networks:
  gsr:
  dmz:
    external: true
