version: "3.5"

name: web2022

services:
    website:
        container_name: website2022
        hostname: website2022
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DATABASE_URL: "postgresql://gsr:gsr@10.0.0.3:5432/mydb?schema=public"
                UPLOAD_DIR: "/app/uploads"
                BODY_SIZE_LIMIT: "Infinity"
        environment:
            DATABASE_URL: "postgresql://gsr:gsr@10.0.0.3:5432/mydb?schema=public"
            UPLOAD_DIR: "/app/uploads"
            PUBLIC_GOOGLE_CALENDAR_API_KEY: "${PUBLIC_GOOGLE_CALENDAR_API_KEY}"
            BODY_SIZE_LIMIT: "Infinity"
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=25728640"
            #- "traefik.http.routers.staging.rule=Host(`gentsestudentenraad.be`, `stura.ugent.be`,`stuart.ugent.be`,`fris.ugent.be`,`stuveco.ugent.be`,`sturec.ugent.be`,`stubio.ugent.be`,`ppsr.ugent.be`,`stuff.ugent.be`,`bsr.ugent.be`, `stugg.ugent.be`, `swop.ugent.be`)"
            - "traefik.http.routers.staging.rule=Host(`gsr.staging.gentsestudentenraad.be`,`stura.staging.gentsestudentenraad.be`,`stuart.staging.gentsestudentenraad.be`,`fris.staging.gentsestudentenraad.be`,`stuveco.staging.gentsestudentenraad.be`,`sturec.staging.gentsestudentenraad.be`,`stubio.staging.gentsestudentenraad.be`,`ppsr.staging.gentsestudentenraad.be`,`stuff.staging.gentsestudentenraad.be`,`bsr.staging.gentsestudentenraad.be`, `stugg.staging.gentsestudentenraad.be`, `swop.staging.gentsestudentenraad.be`)"
            - "traefik.http.routers.staging.entrypoints=websecure"
            - "traefik.http.routers.staging.tls.certresolver=letsencrypt"
            - "traefik.http.services.staging.loadbalancer.server.port=3000"
        volumes:
            - "/home/celeste/nfs-volume/gsr-site-persistent/uploads:/app/uploads"
        networks:
            server_default:
            web2022:
                ipv4_address: 10.0.0.2
        restart: unless-stopped
        depends_on:
            - postgres
    postgres:
        container_name: website-postgres
        hostname: postgres
        image: postgres
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: gsr
            POSTGRES_PASSWORD: gsr
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "/home/celeste/nfs-volume/volumes/staging/postgresql:/var/lib/postgresql/data"
        restart: always
        networks:
            web2022:
                ipv4_address: 10.0.0.3

networks:
    web2022:
        name: web2022
        ipam:
            config:
                - subnet: 10.0.0.0/24
    server_default:
        external: true
