version: '3.9'
services:
  website:
    container_name: website2022
    hostname: website2022
    image: ghcr.io/gentsestudentenraad/website:main
    environment:
      DATABASE_URL: 'postgresql://gsr:gsr@postgres:5432/gsr?schema=public'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.staging.rule=Host(`staging.gentsestudentenraad.be`,`gsr.ugent.be`)'
      - 'traefik.http.routers.staging.entrypoints=websecure'
      - 'traefik.http.routers.staging.tls.certresolver=letsencrypt'
      - 'traefik.http.services.staging.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.test-auth.basicauth.users=gsr:$$apr1$$vNW/TXZ8$$ZEBU.uYb/6e8efHUXsx1w0'
      - 'traefik.http.routers.staging.middlewares=test-auth'
    networks:
      - 'web2022'
      - 'server_default'
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: website-postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_DB: gsr
      POSTGRES_USER: gsr
      POSTGRES_PASSWORD: gsr
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - '/home/jens/volumes/staging/postgresql:/var/lib/postgresql/data'
    restart: always
    networks:
      - 'web2022'

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:v1.8.5
    container_name: appsmith
    volumes:
      - '/home/jens/volumes/admin/stacks:/appsmith-stacks'
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.admin.rule=Host(`admin.gentsestudentenraad.be`)'
      - 'traefik.http.routers.admin.entrypoints=websecure'
      - 'traefik.http.routers.admin.tls.certresolver=letsencrypt'
      - 'traefik.http.services.admin.loadbalancer.server.port=80'
    networks:
      - 'web2022'
      - 'server_default'

  filebrowser:
    image: filebrowser/filebrowser:v2.22.4
    container_name: filebrowser
    volumes:
      - '/home/jens/volumes/web:/srv'
      - '/home/jens/volumes/filebrowser/db:/db'
      - '/home/jens/volumes/filebrowser/.filebrowser.json:/.filebrowser.json'
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.filebrowser.rule=Host(`files.gentsestudentenraad.be`)'
      - 'traefik.http.routers.filebrowser.entrypoints=websecure'
      - 'traefik.http.routers.filebrowser.tls.certresolver=letsencrypt'
      - 'traefik.http.services.filebrowser.loadbalancer.server.port=80'
    networks:
      - 'web2022'
      - 'server_default'
    user: '1012:1012'

networks:
  web2022:
  server_default:
    external: true
