version: "3.5"

name: web2022

services:
    website:
        container_name: website2022
        hostname: website2022
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DATABASE_URL: "postgresql://gsr:gsr@10.0.0.3:5432/gsr?schema=public"
        environment:
            DATABASE_URL: "postgresql://gsr:gsr@10.0.0.3:5432/gsr?schema=public"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.staging.rule=Host(`gsr.staging.gentsestudentenraad.be`,`stura.staging.gentsestudentenraad.be`,`stuart.staging.gentsestudentenraad.be`,`fris.staging.gentsestudentenraad.be`,`stuveco.staging.gentsestudentenraad.be`,`sturec.staging.gentsestudentenraad.be`,`stubio.staging.gentsestudentenraad.be`,`ppsr.staging.gentsestudentenraad.be`,`stuff.staging.gentsestudentenraad.be`,`bsr.staging.gentsestudentenraad.be`)"
            - "traefik.http.routers.staging.entrypoints=websecure"
            - "traefik.http.routers.staging.tls.certresolver=letsencrypt"
            - "traefik.http.services.staging.loadbalancer.server.port=3000"
            - "traefik.http.middlewares.test-auth.basicauth.users=gsr:$$apr1$$vNW/TXZ8$$ZEBU.uYb/6e8efHUXsx1w0"
            - "traefik.http.routers.staging.middlewares=test-auth"
        networks:
            server_default:
            web2022:
                ipv4_address: 10.0.0.2
        volumes:
            - "/home/celeste/volumes/staging/postgresql:/var/lib/postgresql/data"
            - "./uploads:/static/uploads"
        restart: unless-stopped
        depends_on:
            - postgres

    postgres:
        container_name: website-postgres
        hostname: postgres
        image: postgres
        environment:
            POSTGRES_DB: gsr
            POSTGRES_USER: gsr
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "/home/jens/volumes/staging/postgresql:/var/lib/postgresql/data"
        restart: always
        networks:
            web2022:
                ipv4_address: 10.0.0.3

networks:
    web2022:
        name: web2022
        ipam:
            config:
                - subnet: 10.0.0.0/24
    server_default:
        external: true
