name: Linter

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  linter:
    runs-on: ubuntu-latest
    env:
      PRISMA_SKIP_POSTINSTALL_GENERATE: true
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gentesestudentenraad'
      - name: 'Install dependencies'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Check for linting and errors'
        run: npm run lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
